version: "3"
services:
  app:
    command: npm run dev
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
  mongo:
    expose:
      - 27017
    image: mongo
    volumes:
      - ./data/db:/data/db
