version: '3'
services:
    mongo:
        expose:
            - 27017
        image: mongo
        volumes:
            - ./data/db:/data/db
    server:
        command: npm run start
        depends_on:
            - mongo
        environment:
            NODE_ENV: development
        image: node:alpine
        ports:
            - 3000:3000
        restart: always
        volumes:
            - ./:/app
        working_dir: /app
